### ISSUE TITLE
Adding output arguments

### ISSUE THREAD

**Issue by schueppi-com** [Jerome-LMA/oscar#2]
It would be nice to add some output arguments to functions like Get_info.m that these functions can be easily used in external scripts/functions. Otherwise everyone who uses the oscar code would duplicate such code...

**Comment by nilsmelchert** [comment]
I dont know, if i got you right. There are already some ourput args stored in the variable `varargout` with a variable number of output arguments.

What exactly is the enhancement, that you are looking for?

**Comment by schueppi-com** [comment]
The enhancement would look like this new [Get_info.m in my fork](https://github.com/schueppi-com/oscar/blob/more_flexible/Classes/%40Cavity1/Get_info.m). Probably an additional input argument would be also useful to decide whether the plot should be generated.

Actually, we used the oscar code already in that [paper](https://doi.org/10.1364/OE.24.009839) with our collaborator at Paris. Here we copied the Get_info.m file, modified it and saved it with a name like Get_info_no_plot.m... As I currently rewrite our code, I would prefer to make a clear separation of oscar code and our code on top of that without any modification of oscar.
Btw. in the manual at section 1.1.1., there was a note that a minimal Python version also exists. Looks like this Python version existed just a long time ago and isn't available, is it?

**Comment by nilsmelchert** [comment]
@Jerome-LMA What do you think?

**Comment by Jerome-LMA** [comment]
I would not recommend to use "get_info" to extract the parameters from the steady state cavity (that is not the purpose of this function). The best would be to use "Calculate_fields_AC" and then calculate what you need (like for example in "Display_Results")

The python version was written for a summer school, much less advanced and not supported but I should be able to find the files somewhere.

**Comment by schueppi-com** [comment]
Ah okay, I see. It was just compelling to use this function as every parameter I need for my analysis was calculated. Maybe it would be useful to clarify the differences in more detail in the manual at 4.2.6.

Okay, the Python version would probably need a lot of development. So I stay at the MATLAB version to save time. Thanks!

I have two more features to discuss... I'll open new issues for them.

**Comment by Jerome-LMA** [comment]
The get_info() function will not be used in the next version and in the examples it will be replaced by Calculate_Field() which can do the same thing. For speed reason, better even to use  Calculate_Field_AC() if you do not need to see the power buildup.
