### ISSUE TITLE
Arbitrary shifts of mirror surface

### ISSUE THREAD

**Issue by schueppi-com** [Jerome-LMA/oscar#3]
In my case, it is useful to shift the mirror profile by an arbitrary distance. This feature could be easily implemented at the step of creating the mirror surface. In the [branch "shifting" of my fork](https://github.com/schueppi-com/oscar/commit/062f52782c558e36a8fa5577865be19e754da859), the code is shown how you could implement it.

**Comment by Jerome-LMA** [comment]
Re-thanks.
Several times, I have also to do that so in the latest version there is the "centering" option in add_map(). Need to check the sign however.

**Comment by schueppi-com** [comment]
Yes, I've seen the "centering" option, but it didn't allow arbitrary distances. Yes, I haven't check for the sign as for me this is a variable parameter I need to optimize. We should probably also consider the different order of centering which is before the rotation and tilting.

**Comment by Jerome-LMA** [comment]
Added the 'shift' option, implemented your way. I have to change a sign when I try on one example.
