### ISSUE TITLE
Fixing error when fitting tiny E-Fields

### ISSUE THREAD

**Issue by schueppi-com** [Jerome-LMA/oscar#4]
As I work with mirror imprinted on fibers with dimensions in microns, the MATLAB "polyfit" function gives the following Error/Warning: Warning: Polynomial is badly conditioned. Add points with distinct X values, reduce the degree of the polynomial, or try centering and scaling as described in HELP POLYFIT.
You can fix this warning with the scaling feature of the "polyfit" function. A possible code is shown in the [branch "fitting-tiny-e-fields" of my fork](https://github.com/schueppi-com/oscar/commit/7494727ec2cb958ab63ebc9aef7ca958a2059709).

**Comment by Jerome-LMA** [comment]
Thanks!
Your fix will be in the next release.

**Comment by nilsmelchert** [comment]
We can close this issue now imo
